-- Board 게시판 
CREATE TABLE EDUBOARD (
	SEQ NUMBER,
	ID VARCHAR2(20) NOT NULL,
	TITLE VARCHAR2(100) NOT NULL,
	CONTENT VARCHAR2(500) NOT NULL,
	DELFLAG CHAR(1) NOT NULL,
	CREATEAT DATE
);

-- USER 정보
CREATE TABLE EMPINFO(
	ID VARCHAR2(20) NOT NULL,
	PASSWORD VARCHAR2(40) NOT NULL,
	NAME VARCHAR2(20) NOT NULL,
	PHONE VARCHAR2(20) NOT NULL,
	ENABLE CHAR(1) NOT NULL,
	AUTH VARCHAR2(10) NOT NULL,
	PHOTO VARCHAR2(100)
);
					
ALTER TABLE EDUBOARD ADD CONSTRAINT EDUBOARD_PK PRIMARY KEY (SEQ);
ALTER TABLE EMPINFO ADD CONSTRAINT EMPINFO_PK PRIMARY KEY (ID);
ALTER TABLE EDUBOARD ADD CONSTRAINT EDUBOARD_FK FOREIGN KEY (ID) REFERENCES EMPINFO (ID);


-- EMPINFO 더미데이터
INSERT INTO EMPINFO e (ID, PASSWORD, NAME, 
					   PHONE, ENABLE, AUTH)
	VALUES('바보','1234','바보세웅',
			'000-111-1111','Y','U');
		
INSERT INTO EMPINFO e (ID, PASSWORD, NAME, 
					   PHONE, ENABLE, AUTH)
	VALUES('ADMIN','ADMIN','관리자',
			'000-111-1000','Y','A');


		
INSERT INTO EDUBOARD (SEQ, ID, TITLE, CONTENT, DELFLAG, CREATEAT)
		VALUES((SELECT NVL(MAX(SEQ), 0) + 1 FROM EDUBOARD), '바보', '글제목', '글내용', 'N', SYSDATE);


-- 포토 컬럼 추가
ALTER TABLE EMPINFO ADD PHOTO VARCHAR2(100);

ALTER TABLE EMPINFO DROP COLUMN PHOTO;



